# -*- coding: utf-8 -*-
"""tp trombone graph 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jenH7lrW8prDyEqhptEoG7RNx3UoxC0o
"""

import matplotlib.pyplot as plt
import numpy as np
import scipy as sp
from scipy.interpolate import BSpline, make_interp_spline

x = np.array([0, 0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15])
y = np.array([6, 5.2, 3.4, 1, 0.5, 1.8, 3.7, 5.5, 5.6, 3.8, 1.5, 0.2, 0.8, 2.5, 4.3, 5.7, 4.8, 2.5, 0.5, 0.4, 1.6, 3.6, 5.4, 5.2, 3.7, 1.6, 0.3, 1.1, 3.1, 4.8, 5.4 ])

x_new = np.linspace(0,15.5 , 300)

a_BSpline = sp.interpolate.make_interp_spline(x, y)

y_new = a_BSpline(x_new)

plt.plot(x,y, 'o')
plt.plot(x_new, y_new)
plt.legend(["Data", "Fitting curve"], loc='upper right', fontsize='x-small')


plt.xlabel("Delta_d (cm)")
plt.ylabel("yR (volt)")
plt.grid(True)
plt.show()

